using Ardalis.Result;
using MediatR;
using SpaceOS.Modules.Procurement.Domain.Aggregates;
using SpaceOS.Modules.Procurement.Domain.Interfaces;

namespace SpaceOS.Modules.Procurement.Application.Commands.CreateComplaint;

public sealed class CreateComplaintCommandHandler
    : IRequestHandler<CreateComplaintCommand, Result<Guid>>
{
    private readonly IComplaintRepository _repository;

    public CreateComplaintCommandHandler(IComplaintRepository repository)
    {
        _repository = repository;
    }

    public async Task<Result<Guid>> Handle(CreateComplaintCommand request, CancellationToken ct)
    {
        // Create complaint aggregate (complaint number will be generated by repository on insert)
        var result = SupplierComplaint.Create(
            request.TenantId,
            request.SupplierId,
            request.DeliveryId,
            request.PurchaseOrderId,
            request.Type,
            request.Subject,
            request.Description,
            request.AffectedQuantity,
            request.ClaimedAmount,
            request.Currency,
            qaResult: null, // Can be enriched from Delivery later
            request.EvidencePaths,
            request.CreatedBy);

        if (!result.IsSuccess)
            return Result<Guid>.Invalid(result.ValidationErrors.ToArray());

        var complaint = result.Value;

        var addResult = await _repository.AddAsync(complaint, ct).ConfigureAwait(false);
        if (!addResult.IsSuccess)
            return Result<Guid>.Error(string.Join(", ", addResult.Errors));

        var saveResult = await _repository.SaveChangesAsync(ct).ConfigureAwait(false);
        if (!saveResult.IsSuccess)
            return Result<Guid>.Error(string.Join(", ", saveResult.Errors));

        return Result<Guid>.Success(complaint.Id);
    }
}
